set_property SRC_FILE_INFO {cfile:C:/eFPGA/2_Simple_VHDL/2_Simple_VHDL.srcs/constrs_1/new/XDC.xdc rfile:../../../2_Simple_VHDL.srcs/constrs_1/new/XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports clk65MHz]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk65MHz]
