<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{5cdc7a30-3062-499f-b031-3f71cc6725a4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN

VAR
    hServer         : T_HSERVER; 
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Server(hServer := hServer);
Client();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="17" Count="0" />
      <LineId Id="34" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>