set_property PACKAGE_PIN L15 [get_ports {GPIO_tri_io[0]}]
set_property PACKAGE_PIN E12 [get_ports {GPIO_tri_io[1]}]
set_property PACKAGE_PIN E13 [get_ports {GPIO_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_io[0]}]
