set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT[6]}]
set_property PACKAGE_PIN N13 [get_ports {OUTPUT[6]}]
set_property PACKAGE_PIN L13 [get_ports {OUTPUT[5]}]
set_property PACKAGE_PIN K13 [get_ports {OUTPUT[4]}]
set_property PACKAGE_PIN M14 [get_ports {OUTPUT[0]}]

set_property PACKAGE_PIN L15 [get_ports {OUTPUT[3]}]
set_property PACKAGE_PIN M15 [get_ports {OUTPUT[2]}]
set_property PACKAGE_PIN L14 [get_ports {OUTPUT[1]}]
