set_property PACKAGE_PIN M15 [get_ports RT1_0]
set_property PACKAGE_PIN L15 [get_ports RT2_0]
set_property IOSTANDARD LVCMOS33 [get_ports RT2_0]
set_property IOSTANDARD LVCMOS33 [get_ports RT1_0]
set_property IOSTANDARD LVCMOS33 [get_ports {ROT_VAL_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROT_VAL_0[0]}]
set_property PACKAGE_PIN E12 [get_ports {ROT_VAL_0[1]}]
set_property PACKAGE_PIN E13 [get_ports {ROT_VAL_0[0]}]
